### ISSUE TITLE
Dynamic Column display

### ISSUE THREAD

**Issue by roanBBC** [SFDO-Community-Sprints/sticky-selectron-documentation#6]
Provide UI and infrastructure for dynamically defining which columns will display
- in original collection
- in selected collection
columns configured dynamically are also those that will be queried in the search UI.

**Comment by pickettd** [comment]
I looked into this a bit this morning (mostly from the perspective of how to make the LWC flexible enough on parameters that we can release the code/package publicly and not have a big parameter change in the future). At the minimum, I think we want to pass the LWC a collection of fieldNames for the left side columns and a collection of fieldNames for the right side columns.

To match current LWC functionality - in addition to that, it seems like the user could optionally want the ability to label those columns as they wish - so instead of being just a collection of strings (the fieldNames) we'd want collections of <String, String>.

For the eventual best user experience though - we probably want to setup a custom property editor LWC for our sticky-selector and I think [this SF help page shows a way of doing that](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.use_flow_custom_property_editor_sobject_lwc_example).

**Comment by pickettd** [comment]
First version of this is completed and team has tested
